SERVER_HOST = 'localhost'
SERVER_PORT = 35777
SERVER_NAME = f'{SERVER_HOST}:{SERVER_PORT}'
SERVER_VERSION = '0.0.1-beta'
SERVER_FULL_NAME = f'Hanzo Authentication and Authorisation Server - {SERVER_VERSION}'

MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
MONGODB_DATABASE = 'hanzo'
MONGODB_USER = 'hanzo'
MONGODB_PASSWORD = 'krrdvPU2QfUvFmAQX5l3Z'

MONGO_URI = f'mongodb://{MONGODB_USER}:{MONGODB_PASSWORD}@{MONGODB_HOST}:{MONGODB_PORT}/{MONGODB_DATABASE}'

SECRET_KEY = 'hanzo'

JWT_SECRET_KEY='(qii[hwdX%OHb02^uqM9#BfuzQX>lTwId*3dcdts<v'
JWT_ACCESS_TOKEN_EXPIRES = 8
JWT_REFRESH_TOKEN_EXPIRES = 30
